name: Frontend CI

# Робот будет запускаться при любом Pull Request в ветку dev
on:
  pull_request:
    branches: [ dev ]

jobs:
  validate-code:
    runs-on: ubuntu-latest # Проверка запустится на удаленном сервере Linux

    steps:
      # 1. Скачиваем ваш код из репозитория на сервер проверки
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Устанавливаем Node.js нужной версии
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm install --force

      - name: Run ESLint (Проверка на баги)
        run: npm run lint

      - name: Run Unit Tests
        run: npm run test

      - name: Run Prettier Check (Проверка форматирования)
        run: npm run format:check

      - name: Check TypeScript types
        run: npm run build

